### ISSUE TITLE
offset方法在一种情况下会失效 

### ISSUE THREAD

**Issue by hxzpily2** [Chimeejs/chimee-plugin-popup#1]
假设我初始化popupFactory    offset设置为: '0px auto auto auto',
在调用 offset方法设置  'auto auto 25px 25px'
源码中遇到auto 就忽略了 就导致第一个0px 是无法去掉的
css 中有top 0px 
本该右下角 变成右上角了

**Comment by huzunjie** [comment]
谢谢反馈，已经修正
