### ISSUE TITLE
chimee-plugin-popup插件安装后，如何更新popup中的body内容？

### ISSUE THREAD

**Issue by qwe9527** [Chimeejs/chimee-plugin-popup#3]
Chimee.install(chimeePluginPopup({
name: 'cc_popup',
title: '这是一个居中信息框',
body: '这里是信息内容',
offset: '50% 50%',
width: '200px'
}));
const player = new Chimee({
src: 'http://cdn.toxicjohann.com/lostStar.mp4',
type: 'vod',
box: 'mp4',
wrapper: '#wrapper',
plugin: ['cc_popup'],
auto: true
});

如何在install之后更新body的内容？

**Comment by huzunjie** [comment]
你可以 `player.ccPopup.$dom.querySelector('cm-pp-body').innerHTML='xxxxx'` 来改写body展示的内容。

另外，body 内可以写HTML代码，这样你可以通过直接操作目标DOM元素，在需要的时机改写对应内容。
